# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master
- dev/*

jobs:
- job: 'mac'
  pool:
    vmImage: 'macos-latest'

  steps:
    - script: |
        cd ByteDance290101/mac && ./sync.sh && ./release.sh
      displayName: 'Build ByteDance290101'
    - publish: 'ByteDance290101/mac/build/bytedance-mac.zip'
      artifact: 'ByteDancePluginMac290101'

- job: 'win'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - bash: 'cd FaceUnityPlugin/win && ./release.sh'
    - task: VSBuild@1
      inputs:
        solution: 'FaceUnityPlugin\win\FaceUnityPlugin.sln'
        vsVersion: '15.0'
        msbuildArchitecture: 'x86'
        platform: 'x86'
        configuration: 'Release'
    - bash: 'cd FaceUnityPlugin/win && ./package.sh'
    
    - bash: 'cd FaceUnityPlugin-2.9.0/win && ./release.sh'
    - task: VSBuild@1
      inputs:
        solution: 'FaceUnityPlugin-2.9.0\win\FaceUnityPlugin.sln'
        vsVersion: '15.0'
        msbuildArchitecture: 'x86'
        platform: 'x86'
        configuration: 'Release'
    - bash: 'cd FaceUnityPlugin-2.9.0/win && ./package.sh'
    - publish: 'FaceUnityPlugin/win/fu-win.zip'
      artifact: 'FaceUnityPluginWin'
    - publish: 'FaceUnityPlugin-2.9.0/win/fu-win-290.zip'
      artifact: 'FaceUnityPluginWin290'
