# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master
- dev/*

jobs:
- job: 'mac'
  pool:
    vmImage: 'macos-latest'

  steps:
    - script: |
        cd ByteDance290101/mac && ./sync.sh && ./release.sh
      displayName: 'Build ByteDance290101'
    - publish: 'ByteDance290101/mac/build/bytedance-mac.zip'
      artifact: 'ByteDancePluginMac290101'

- job: 'win'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - bash: 'cd ByteDance290101/win && ./sync.sh && ./build.sh'
    - task: VSBuild@1
      inputs:
        solution: 'ByteDance290101\win\ByteDancePlugin.sln'
        vsVersion: '15.0'
        msbuildArchitecture: 'x86'
        platform: 'x86'
        configuration: 'Release'
    - bash: 'cd ByteDance290101/win && ./package.sh'
    - publish: 'ByteDance290101/win/bytedance-win.zip'
      artifact: 'ByteDancePluginWin290101'
